modules := "access org-read"

# format terraform files
format:
    terraform fmt -recursive

# lint files
lint: _lint-format _lint-validate _lint-tflint


_lint-format:
    terraform fmt -recursive --check

_lint-validate:
    #!/usr/bin/env bash
    set -e

    for module in {{modules}}; do
      terraform -chdir="$module" init
      terraform -chdir="$module" validate
    done

_lint-tflint:
    #!/usr/bin/env bash
    set -e

    for module in {{modules}}; do
      tflint -f compact --recursive --chdir "$module"
    done

# update autogenerated documentation
docs:
    #!/usr/bin/env bash
    set -e

    for module in {{modules}}; do
      terraform-docs markdown "$module" --output-file README.md
    done
